version: '2'
services:
  kops:
    image: airhelp/kops:1.6.2
    volumes:
      - ./.ssh:/root/.ssh:ro
      - ./.aws:/root/.aws:ro
      - ./.kube:/root/.kube:rw
      - .workdir:/workdir
    working_dir: /workdir
    env_file:
      - .env
  aws:
    image: cgswong/aws:aws
    volumes:
      - ./.aws:/root/.aws
      - .workdir:/workdir
    working_dir: /workdir

