version: '2'
services:
  kops:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - .aws:/root/.aws:ro
      - .kube:/root/.kube:rw
      - .workdir:/workdir
    working_dir: /workdir
    env_file:
      - .env
  helm:
    image: lachlanevenson/k8s-helm:v2.7.2
    volumes:
      - .kube:/root/.kube:rw
      - .workdir:/workdir
      - .helm:/root/.helm:rw
    working_dir: /workdir
  aws:
    image: cgswong/aws:aws
    volumes:
      - .aws:/root/.aws
      - .workdir:/workdir
    working_dir: /workdir
  kubectl_proxy:
    image: airhelp/kops:1.6.2
    volumes:
      - .kube:/root/.kube:rw
    entrypoint: /bin/ash
    command: -c "kubectl proxy --address=\"0.0.0.0\" --port=9090 --accept-hosts '.*' --reject-methods=NONE"
    ports:
      - "9090:9090"

